import Auth from "@/components/authComponent/Register";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import Random from "./_auth/Auth";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>

        <title>LifeScript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Auth/>
      </main>
    </div>
  );
}
