import { Inter } from "next/font/google";
import Head from "next/head";
import AuthPage from "./_auth/Auth";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App My app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AuthPage />
    </>
  );
}
