export const subBasicList = [
  {
    label: "Spelling and grammar assistance",
  },
  {
    label: "Automatic Photo Improvement",
  },
  {
    label: "Text Formatting Features",
  },
];
export const subStandardList = [
  {
    label: "Spelling and grammar assistance",
  },
  {
    label: "Automatic Photo Improvement",
  },
  {
    label: "Text Formatting Features",
  },
  {
    label: "Narrative fusion",
  },
  {
    label: "Voice-to-text ",
  },
  {
    label: "Family Tree ",
  },
];

export const subPremiumList = [
  {
    label: "Spelling and grammar assistance",
  },
  {
    label: "Automatic Photo Improvement",
  },
  {
    label: "Text Formatting Features",
  },
  {
    label: "Narrative fusion",
  },
  {
    label: "Voice-to-text",
  },
  {
    label: "Family Tree",
  },
  {
    label: "Premium Book Covers",
  },
  {
    label: "Priority Customer Support",
  },
  {
    label: "Exclusive access to new features",
  },
];



export const quotes = (t) => [
  t("quotes.quote1"),
  t("quotes.quote2"),
  t("quotes.quote3"),
  t("quotes.quote4"),
  t("quotes.quote5"),
  t("quotes.quote6"),
  t("quotes.quote7"),
  t("quotes.quote8"),
  t("quotes.quote9"),
  t("quotes.quote10"),
  t("quotes.quote11"),
  t("quotes.quote12"),
  t("quotes.quote13"),
  t("quotes.quote14"),
  t("quotes.quote15"),
  t("quotes.quote16"),
  t("quotes.quote17"),
  t("quotes.quote18"),
  t("quotes.quote19"),
  t("quotes.quote20"),
  t("quotes.quote21"),
  t("quotes.quote22"),
  t("quotes.quote23"),
  t("quotes.quote24"),
  t("quotes.quote25"),
  t("quotes.quote26"),
  t("quotes.quote27"),
  t("quotes.quote28"),
  t("quotes.quote29"),
  t("quotes.quote30"),
  t("quotes.quote31"),
  t("quotes.quote32"),
  t("quotes.quote33"),
  t("quotes.quote34"),
  t("quotes.quote35"),
  t("quotes.quote36"),
  t("quotes.quote37"),
  t("quotes.quote38"),
  t("quotes.quote39"),
  t("quotes.quote40"),
  t("quotes.quote41"),
  t("quotes.quote42"),
  t("quotes.quote43"),
  t("quotes.quote44"),
  t("quotes.quote45"),
  t("quotes.quote46"),
  t("quotes.quote47"),
  t("quotes.quote48"),
  t("quotes.quote49"),
  t("quotes.quote50"),
  t("quotes.quote51"),
  t("quotes.quote52"),
  t("quotes.quote53"),
  t("quotes.quote54"),
  t("quotes.quote55"),
  t("quotes.quote56"),
  t("quotes.quote57"),
  t("quotes.quote58"),
  t("quotes.quote59"),
  t("quotes.quote60"),
  t("quotes.quote61"),
  t("quotes.quote62"),
  t("quotes.quote63"),
  t("quotes.quote64"),
  t("quotes.quote65"),
  t("quotes.quote66"),
  t("quotes.quote67"),
  t("quotes.quote68"),
  t("quotes.quote69"),
  t("quotes.quote70"),
  t("quotes.quote71"),
  t("quotes.quote72"),
  t("quotes.quote73"),
  t("quotes.quote74"),
  t("quotes.quote75"),
  t("quotes.quote76"),
  t("quotes.quote77"),
  t("quotes.quote78"),
  t("quotes.quote79"),
  t("quotes.quote80"),
  t("quotes.quote81"),
  t("quotes.quote82"),
  t("quotes.quote83"),
  t("quotes.quote84"),
  t("quotes.quote85"),
  t("quotes.quote86"),
  t("quotes.quote87"),
  t("quotes.quote88"),
  t("quotes.quote89"),
  t("quotes.quote90"),
  t("quotes.quote91"),
  t("quotes.quote92"),
  t("quotes.quote93"),
  t("quotes.quote94"),
  t("quotes.quote95"),
  t("quotes.quote96"),
  t("quotes.quote97"),
  t("quotes.quote98"),
  t("quotes.quote99"),
  t("quotes.quote100"),
  t("quotes.quote101"),
  t("quotes.quote102"),
  t("quotes.quote103"),
  t("quotes.quote104"),
  t("quotes.quote105"),
  t("quotes.quote106"),
  t("quotes.quote107"),
  t("quotes.quote108"),
  t("quotes.quote109"),
  t("quotes.quote110"),
];