
import { Box, Typography } from "@mui/material";
import NavBar from "@/__webComponents/navBar/NavBar";
import styles from "./Terms.module.css"

import Logo from "@/__webAssets/svgs/lifescript-life-story-book-logo.svg"

const TermsAndConditions = () => {
  const keyTerms = [
    {
      title: "Cookie:",
      text: "A small amount of data generated by our Website and saved by your web browser, used for identification, analytics, and remembering your preferences."
    },
    {
      title: "Company:",
      text: "LifeScript Ltd., which refers to 'we,' 'us, ' or 'our' in these Terms. Country: Bulgaria, where LifeScript Ltd.is based."
    },
    {
      title: "Country: ",
      text: "Bulgaria, where LifeScript Ltd. is based."
    },
    {
      title: "Device:",
      text: "Any internet-connected device such as a phone, tablet, or computer used to access LifeScript's Services."
    },
    {
      title: "Service:",
      text: " The service provided by LifeScript as described in these Terms and on our platform."
    },
    {
      title: "Third-party service:",
      text: "External entities such as advertisers, contest sponsors, promotional and marketing partners whose products or services may be of interest. "
    },
    {
      title: "Website: ",
      text: "LifeScript's site, accessible via www.theLifeScript.com."
    },
    {
      title: "You:",
      text: "A person or entity registered with LifeScript to use the Services."
    },
  ]

  const generalTerms = [
    {
      title: "Acceptance of Terms",
      text: "By accessing LifeScript, you confirm your agreement with and are bound by these Terms"
    },
    {
      title: "License:",
      text: "We grant you a revocable, non-exclusive, non-transferable, limited license to use the Website and Services in accordance with these Terms."
    },
    {
      title: "Use of Services:",
      text: "Your use of our Services must comply with all applicable laws. Misuse of our Services is prohibited."
    },
    {
      title: "Age Requirement:",
      text: "You must be at least 18 years old to use our Services."
    },
    {
      title: "Liability:",
      text: " LifeScript is not liable for damages arising from your use or inability to use our Website or Services."
    },
    {
      title: "Modification and Termination of Services: ",
      text: "We reserve the right to modify or discontinue Services and may terminate or suspend your access for any breach of these Terms."
    },
    {
      title: "Changes to Terms:",
      text: "These Terms may be updated periodically. Continued use of the Services signifies acceptance of the revised Terms."
    },
    {
      title: "Privacy Policy:",
      text: "Your use of our Services is also governed by our Privacy Policy."
    },
  ]

  const payment = [
    {
      title: "Payment Terms:",
      text: "You agree to pay all fees or charges to your account for the Service in accordance with the fees, charges, and billing terms in effect at the time each fee or charge is due and payable. Subscription to any of the pricing plans requires you to provide a valid credit card (Visa, MasterCard, or any other issuer we accept) as a condition to signing up. The agreement with your Payment Provider governs the use of your designated credit card account, and you should refer to that agreement, not these Terms, to understand your rights and liabilities. "
    },
    {
      title: "Billing Authorization: ",
      text: "By providing LifeScript with your credit card number and associated payment information, you authorize us to verify information immediately and to invoice your account for all fees and charges due and payable to LifeScript under these terms. This authorization means that no additional notice or consent is required for billing. We reserve the right to change prices and billing methods at any time upon posting on our website."
    },
    {
      title: "Collection and Fees:",
      text: "Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed amounts will be your responsibility. A contract for the Service between you and LifeScript is established only after LifeScript accepts your order via confirmatory e-mail or other appropriate means of communication. You are also responsible for any third-party fees incurred when using the Service."
    },
    {
      title: "Product Purchases: ",
      text: "When purchasing our products, you will be required to supply certain information relevant to your purchase, including payment details. This information will be handled in accordance with our Privacy Policy. Prices and product offerings on our website are subject to change without notice. We reserve the right, with or without prior notice, to limit product quantities, discontinue products, decide on promotional offers, restrict purchases, or refuse service. Replacement of products with printing defects or shipping damage will be done upon receiving photographic evidence for our documentation."
    },
    {
      title: "Warranty and Additional Information:",
      text: "Please be aware that while we aim to offer reliable and user-friendly Services, we do not provide warranties with respect to the Services. For additional information related to shipping, returns, and refunds, please refer to our FAQs. By engaging with our services and making purchases, you acknowledge and agree to these terms as part of our broader Terms of Use policy."
    },
  ]
  return (
    <Box className={styles.terms}>
      <NavBar color="#F3ECDA" logo={Logo} />

      <Box sx={{ display: "flex", justifyContent: "center", alignItems: "center" }}>

        <Box sx={{ margin: { md: "200px 0 150px", sm: "150px 50px", xs: "120px 20px" }, maxWidth: { lg: "1050px", md: "850px", sm: "100%" } }}>
          <Box sx={{ textAlign: "center" }}>
            <Typography sx={{ fontSize: { md: "52px", sm: "44px", xs: "32px" }, fontFamily: "Basely !important", fontWeight: 500 }}>Terms of Use</Typography>
            <Typography>Updated at January 30th, 2024</Typography>
          </Box>
          <Typography sx={{ margin: { sm: "80px 0 50px", xs: "40px 0 30px" } }}>Welcome to LifeScript, a platform dedicated to capturing and preserving life stories. By accessing and using the services provided by LifeScript (&quot;Service&quot;), you engage with LifeScript Ltd., located at 16 Avgusta Trayana, Stara Zagora, Bulgaria (&quot;Company&quot;).This document, the Terms of Use (&quot;Terms&quot;), governs your access to and use of our Services, including our website located at www.theLifeScript.com (&quot;Website&quot;). These Terms form a binding contract between you and LifeScript Ltd. If you do not agree to these Terms, you should not use the LifeScript Service</Typography>


          <PHeading text="Definitions and Key Terms" />
          <Typography sx={{ margin: "10px 0" }}>To ensure clarity, the following terms are defined as follows:</Typography>
          <Box sx={{ maxWidth: "900px" }}>
            <Box sx={{ maxWidth: "90%", margin: { sm: "0 0 50px 20px", xs: "0 0 30px 20px" } }}>
              {keyTerms.map((item, index) => <Point
                key={index}
                title={item.title}
                text={item.text}
              />)}
            </Box>

            <PHeading text="General Terms of Use" />
            <Box sx={{ maxWidth: "90%", margin: { sm: "20px 0 50px 20px", xs: "10px 0 30px 20px" } }}>
              {generalTerms.map((item, index) => <Point
                key={index}
                title={item.title}
                text={item.text}
              />)}
            </Box>
            <Text text="By using LifeScript&apos;s Services, you acknowledge that you have read, understood, and agree to be bound by these Terms, including the definitions and key terms. For any inquiries or questions regarding these Terms, please contact us at info@theLifeScript.com" />

            <PHeading text="User-Generated Content: Rights, Responsibilities, and Usage" />
            <Text text="At LifeScript, we respect the intellectual property rights of our users. When you upload or otherwise provide written materials, photographs, voice and/or video recordings, or other content (collectively, the “Content”) to our platform, you retain ownership of any intellectual property rights in that Content. By submitting your Content, you grant LifeScript a worldwide, perpetual, sublicensable, and transferable license to use the Content to provide our Services to you and for any other purpose you have agreed to, such as marketing purposes. Despite this license, the ownership of your Content remains with you, and we will only use the Content as mutually agreed upon. Please note that while you maintain ownership of your Content, any template or layout in which you arrange or organize such Content through tools and features made available by LifeScript is proprietary to us and will remain with LifeScript. You bear full responsibility for the Content you share with us. If you choose to share the Content publicly, you do so at your own risk, and LifeScript is not liable for any users’ actions in relation to such Content." />

            <Text text="You represent and warrant that you either own the Content or have the necessary rights to share it with us and allow its use as outlined herein, ensuring that the Content does not infringe, misappropriate, or violate any third-party intellectual property or other rights. For any Content featuring individuals, particularly in videos or photos used for marketing purposes, you must secure permission from all individuals depicted, and if any individual is a minor, consent must be obtained from their parent or guardian." margin="20px 0" />

            <Text text="While LifeScript does not typically review customer Content, we may, during the course of providing our Services or in support activities, encounter Content. If we find Content that we determine is illegal or violates our policies, we reserve the right to remove, filter, or refuse to display such Content. However, this does not imply a regular review of Content, so users should not assume such oversight. We are not responsible for any loss or removal of your Content, and we recommend maintaining back-up copies for your records. Additionally, any feedback or suggestions submitted about our Services may be used by LifeScript without any obligation to you." />

            <PHeading text="Restrictions" />
            <Text margin="0 0 20px" text="You agree not to, and you will not permit others to:" />

            <Box sx={{ marginLeft: "20px" }}>
              <ul>
                <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform
                  available to any third party.</li>
                <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
                <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of LifeScript or its affiliates, partners,
                  suppliers or the licensors of the website.</li>
              </ul>
            </Box>
            <PHeading text="Payment" />
            <Text margin="0 0 20px" text="Thank you for considering LifeScript. As you explore our products, we are committed to providing you with exceptional service and value. By registering for any of our subscription plans, you acknowledge and agree to the following terms and conditions, which form an integral part of our Terms of Use." />
            <Box sx={{ maxWidth: "90%", margin: { sm: "0 0 50px 20px", xs: "0 0 30px 20px" } }}>
              {payment.map((item, index) => <Point
                key={index}
                title={item.title}
                text={item.text}
              />)}
            </Box>
            <PHeading text="Intellectual Property and Content Submission" />
            <Text text="When you submit or upload written materials, photographs, voice and/or video recordings, or other content (collectively, the “Content”) to LifeScript, you retain ownership of any intellectual property rights in that Content. However, by submitting Content, you grant LifeScript a worldwide, perpetual, sublicensable, and transferable license to use, adapt, modify, and display the Content in connection with providing LifeScript's services and for any other purposes agreed upon with you, such as marketing. Please be aware that while you maintain ownership of your Content, any format, template, or layout used to arrange or organize such Content through LifeScript's tools and features is proprietary to LifeScript and remains with us" />
            <Text margin="20px 0" text="You bear full responsibility for the Content you share with us. Should you choose to share the Content publicly, you do so at your own risk. LifeScript is not liable for any actions taken by other users regarding your Content. You affirm and warrant that:" />
            <Box sx={{ marginLeft: "20px" }}>
              <ul>
                <li>You either own the Content or have the necessary rights to submit it to LifeScript and to grant us the license to use it as specified</li>
                <li>The Content does not infringe upon, misappropriate, or otherwise violate any intellectual property or other rights of a third party.</li>
              </ul>
            </Box>
            <Text text="In instances where your Content includes videos or photos featuring other individuals, you are required to obtain their consent for sharing the Content with LifeScript. For individuals under the age of 18, consent must be obtained from their parent or guardian." />
            <Text margin="20px 0" text="While LifeScript does not habitually review user-submitted Content, we may encounter a subset of it in the course of providing our services, such as during customer support interactions. If we identify Content that is illegal or violates our policies, we reserve the right to remove, filter, or refuse to display such Content. This does not imply regular review of Content, so users should not presume such monitoring." />
            <Text text="We are not responsible for any loss, damage, or removal of your Content. It is advisable to maintain backup copies of your Content. Feedback or suggestions submitted about our services may be used by us without any obligation to you." />
            <PHeading text="Intellectual Property Rights" />
            <Text text="As stated above, you maintain the intellectual property rights of the content you submit. Using LifeScript's services does not grant you ownership of any intellectual property rights in our services or any content accessed through them. You may not use content from our services unless you obtain permission from its owner or are authorized by law." />
            <Text margin="20px 0 0" text="These terms do not confer the right to use any branding or logos of LifeScript. If you wish to use LifeScript's branding or logo, please contact us at info@theLifeScript.com to request permission. You must not (i) remove, obscure, or alter any legal notices displayed in or alongside our services, or (ii) modify, adapt, translate, distribute, publicly display, reverse engineer, decompile, or disassemble any portion of our services" />
            <PHeading text="Service Modifications, User Agreement, and Terms of Use Updates" />
            <Text text="LifeScript is dedicated to the continuous improvement and evolution of our Services. We reserve the right to modify, suspend, or discontinue any aspect of our website or Services, either temporarily or permanently, with or without notice to you, and without incurring liability. This includes the right to add, alter, or remove functionalities, features, or limits of our Services. Your continued use of the Services indicates your acceptance of such changes. However, if you are not satisfied with our Services, please contact us so we can attempt to resolve any issues. We value the content you create and share using our Services and aim to preserve your access to it. In instances where we discontinue a part of our Services, we will endeavor, where reasonably possible, to provide you with advance notice and an opportunity to retrieve your content." />
            <Text margin="20px 0 0" text="This Agreement is effective until terminated by either you or LifeScript. LifeScript may terminate this Agreement at any time, for any reason, with or without notice. Should you fail to comply with any provision of this Agreement, it will result in immediate termination without notice. Termination does not limit LifeScript's rights or remedies at law or in equity, especially in cases of breach of this Agreement by you. LifeScript also reserves the right to revise these Terms at any time by posting an updated version to our website. You acknowledge and agree that changes to our Terms of Use will be posted on this page, and the Terms of Use modification date will be updated accordingly. You are encouraged to visit this page periodically to review the most current terms, as they are binding on you. By continuing to access or use our services after updated terms have been posted, you agree to be bound by the updated terms. You may stop using the Service at any time without needing to specifically inform LifeScript. If you do not agree to the modified terms for our service, you should discontinue your use of LifeScript services." />
            <PHeading text="Third-Party Services and Social Media Integration" />
            <Text text="Our Services at LifeScript may showcase or provide pathways to Third-Party Services, which include, but are not limited to, external content, websites, applications, and other products or services. Although we strive to collaborate with reliable third parties, LifeScript does not exert control over these Third-Party Services. Consequently, we cannot guarantee their reliability, legality, accuracy, or any other aspects of their content and operation. We also do not endorse, approve, or assume responsibility for any Third-Party Services, including their privacy practices or content." />
            <Text margin="20px 0" text="You agree that your engagement with any Third-Party Services, as well as your reliance on any of their content, products, advertising, or other materials, is solely at your own risk and is governed by the terms and conditions set forth by those services." />
            <Text text="In addition, LifeScript may enable optional integrations with various social media and service providers (e.g., Facebook, Google). Should you choose to connect your LifeScript account with such Third-Party Services, you allow us to access, use, and store the relevant content from these platforms (such as photos or contacts) for exclusive use within our Services. It's important to note that your ability to disable these connections is always available. " />
            <Text margin="20px 0 0" text="Remember, your interactions with these Social Network Providers, including any content you provide to them, are subject to your agreements with them, and LifeScript bears no responsibility for these interactions and content outside our Services." />
            <PHeading text="Copyright Infringement Notice" />
            <Text margin="0 0 20px" text="We are not obliged to review content for copyright or trademark infringement; however, we are dedicated to protecting copyrights and trademarks and expect users of LifeScript to do the same. If you are a copyright owner or such owner’s agent and believe any material on our website constitutes an infringement on your copyright, please contact us setting forth the following information: " />
            <Box sx={{ marginLeft: "20px" }}>
              <ol>
                <li>A physical or electronic signature of the copyright owner or a person authorized to act on his behalf; </li>
                <li>Identification of the material that is claimed to be infringing; </li>
                <li>Your contact information, including your address, telephone number, and an email; </li>
                <li>A statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; </li>
                <li>A statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.</li>
              </ol>
            </Box>
            <PHeading text="Indemnification" />
            <Text text="You agree to indemnify and hold LifeScript and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the website; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party." />
            <PHeading text="No Warranties" />
            <Text text="We provide our Services using a commercially reasonable level of skill and care and we hope that you will enjoy using them, but we do not make any promises about our Services. For example, we don’t make any commitments about the content within the services, the specific function of the services, or their reliability, availability, or ability to meet your needs. We provide the services “as is”. Some jurisdictions provide for certain warranties, like the implied warranty of merchantability, fitness for a particular purpose and non-infringement. To the extent permitted by law, we exclude all implied warranties" />
            <PHeading text="Limitation of Liability" />
            <Text text="Notwithstanding any damages that you might incur, the entire liability of LifeScript and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the service (or if you have not paid anything to us, then 60$)" />
            <Text margin="20px 0" text="To the maximum extent permitted by applicable law, in no event shall LifeScript or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website, third-party software and/or third-party hardware used with the website, or otherwise in connection with any provision of this Agreement), even if LifeScript or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose." />
            <Text text="Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you." />
            <PHeading text="Severability" />
            <Text text="If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect." />
            <Text margin="20px 0" text="This Agreement, together with the Privacy Policy and any other legal notices published by LifeScript on the Services, shall constitute the entire agreement between you and LifeScript concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and LifeScript’s failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND LifeScript AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED." />

            <PHeading text="Waiver" />
            <Text text="Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not affect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute waiver of any subsequent breach." />
            <Text margin="20px 0" text="No failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern." />
            <PHeading text="Agreement to Arbitrate" />
            <Text text="This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR LifeScript’S INTELLECTUAL PROPERTY RIGHTS. The term “dispute” means any dispute, action, or other controversy between you and LifeScript concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. “Dispute” will be given the broadest possible meaning allowable under law." />
            <PHeading text="Notice of Dispute" />
            <Text text="In the event of a dispute, you or LifeScript must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to: info@theLifeScript.com. LifeScript will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and LifeScript will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or LifeScript may commence arbitration." />
            <PHeading text="Binding Arbitration" />
            <Text text="If you and LifeScript don’t resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the International Chamber of Commerce (ICC). Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party’s rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party." />
            <PHeading text="Privacy and Submissions" />
            <Text text="At LifeScript, we are deeply committed to the privacy and protection of your personal stories and data. Our Privacy Policy, which can be found at LINK, outlines the methods we employ to safeguard your personal information while you use our Services. By utilizing our Services, you consent to LifeScript's use of such data in accordance with this Privacy Policy. " />
            <Text margin="20px 0" text="Furthermore, if you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data, or proposals, including new or improved products, services, features, technologies, or promotions, you agree that these submissions will be considered non-confidential and non-proprietary. They will automatically become the exclusive property of LifeScript, with no compensation or acknowledgment owed to you. LifeScript and its affiliates are free to use the ideas from these submissions in any way, across any medium, indefinitely. This includes the right to develop, produce, and market products and services based on these ideas.
" />
            <PHeading text="Miscellaneous" />
            <Text text="If for any reason a court of competent jurisdiction finds any provision or portion of these Terms of Use to be unenforceable, the remainder of these Terms of Use will continue in full force and effect. Any waiver of any provision of these Terms of Use will be effective only if in writing and signed by an authorized representative of LifeScript. LifeScript will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. LifeScript operates and controls the LifeScript Service from its offices in Bulgaria. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the LifeScript Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms of Use (which include and incorporate the LifeScript Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and LifeScript concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import." />
            <PHeading text="Contact Us" />
            <Typography> Should you find yourself dissatisfied with our Services, we encourage you to get in touch with us. Our aim is to settle matters in a friendly manner, and we are committed to addressing your concerns effectively. For any assistance or to discuss your issues, please feel free to email us at <a href="mailto:info@theLifeScript.com" className={styles.url}>info@theLifeScript.com</a>, or you can also reach us by phone at <a href="tel:+359888771442" className={styles.url}>+359888771442</a> .</Typography>
          </Box>
        </Box>
      </Box>

    </Box>
  )
}

export default TermsAndConditions;

function PHeading({ text }) {
  return <Typography sx={{ fontFamily: "Avenir8 !important", fontSize: { md: "32px", sm: "24px", xs: "20px" }, margin: { md: "50px 100px 20px 0", xs: "30px 0 10px" } }}>{text}</Typography>
}

function Text({ text, margin }) {
  return <Typography sx={{ margin: margin }}>{text}</Typography>
}

function Point({ title, text }) {
  return <Box sx={{
    marginBottom: { md: "20px", xs: "10px" }
  }}>
    <Typography sx={{
      fontFamily: "Avenir8 !important",
      marginBottom: "5px"
    }}>{title}
    </Typography>
    <Typography>{text}</Typography>
  </Box>
}