
import { Box, Typography } from "@mui/material";
import NavBar from "@/__webComponents/navBar/NavBar";
import styles from "./Terms.module.css"

import Logo from "@/__webAssets/svgs/logo-footer.svg"

const TermsAndConditions = () => {
  const keyTerms = [
    {
      title: "Cookie:",
      text: "A small amount of data generated by our Website and saved by your web browser, used for identification, analytics, and remembering your preferences."
    },
    {
      title: "Company:",
      text: "Lifescript Ltd., which refers to 'we,' 'us, ' or 'our' in these Terms. Country: Bulgaria, where Lifescript Ltd.is based."
    },
    {
      title: "Country: ",
      text: "Bulgaria, where Lifescript Ltd. is based."
    },
    {
      title: "Device:",
      text: "Any internet-connected device such as a phone, tablet, or computer used to access Lifescript's Services."
    },
    {
      title: "Service:",
      text: " The service provided by Lifescript as described in these Terms and on our platform."
    },
    {
      title: "Third-party service:",
      text: "External entities such as advertisers, contest sponsors, promotional and marketing partners whose products or services may be of interest. "
    },
    {
      title: "Website: ",
      text: "Lifescript's site, accessible via www.thelifescript.com."
    },
    {
      title: "You:",
      text: "A person or entity registered with Lifescript to use the Services."
    },
  ]

  const generalTerms = [
    {
      title: "Acceptance of Terms",
      text: "By accessing Lifescript, you confirm your agreement with and are bound by these Terms"
    },
    {
      title: "License:",
      text: "We grant you a revocable, non-exclusive, non-transferable, limited license to use the Website and Services in accordance with these Terms."
    },
    {
      title: "Use of Services:",
      text: "Your use of our Services must comply with all applicable laws. Misuse of our Services is prohibited."
    },
    {
      title: "Age Requirement:",
      text: "You must be at least 18 years old to use our Services."
    },
    {
      title: "Liability:",
      text: " Lifescript is not liable for damages arising from your use or inability to use our Website or Services."
    },
    {
      title: "Modification and Termination of Services: ",
      text: "We reserve the right to modify or discontinue Services and may terminate or suspend your access for any breach of these Terms."
    },
    {
      title: "Changes to Terms:",
      text: "These Terms may be updated periodically. Continued use of the Services signifies acceptance of the revised Terms."
    },
    {
      title: "Privacy Policy:",
      text: "Your use of our Services is also governed by our Privacy Policy."
    },
  ]

  const payment = [
    {
      title: "Payment Terms:",
      text: "You agree to pay all fees or charges to your account for the Service in accordance with the fees, charges, and billing terms in effect at the time each fee or charge is due and payable. Subscription to any of the pricing plans requires you to provide a valid credit card (Visa, MasterCard, or any other issuer we accept) as a condition to signing up. The agreement with your Payment Provider governs the use of your designated credit card account, and you should refer to that agreement, not these Terms, to understand your rights and liabilities. "
    },
    {
      title: "Billing Authorization: ",
      text: "By providing Lifescript with your credit card number and associated payment information, you authorize us to verify information immediately and to invoice your account for all fees and charges due and payable to Lifescript under these terms. This authorization means that no additional notice or consent is required for billing. We reserve the right to change prices and billing methods at any time upon posting on our website."
    },
    {
      title: "Collection and Fees:",
      text: "Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed amounts will be your responsibility. A contract for the Service between you and Lifescript is established only after Lifescript accepts your order via confirmatory e-mail or other appropriate means of communication. You are also responsible for any third-party fees incurred when using the Service."
    },
    {
      title: "Product Purchases: ",
      text: "When purchasing our products, you will be required to supply certain information relevant to your purchase, including payment details. This information will be handled in accordance with our Privacy Policy. Prices and product offerings on our website are subject to change without notice. We reserve the right, with or without prior notice, to limit product quantities, discontinue products, decide on promotional offers, restrict purchases, or refuse service. Replacement of products with printing defects or shipping damage will be done upon receiving photographic evidence for our documentation."
    },
    {
      title: "Warranty and Additional Information:",
      text: "Please be aware that while we aim to offer reliable and user-friendly Services, we do not provide warranties with respect to the Services. For additional information related to shipping, returns, and refunds, please refer to our FAQs. By engaging with our services and making purchases, you acknowledge and agree to these terms as part of our broader Terms of Use policy."
    },
  ]
  return (
    <Box className={styles.terms}>
      <NavBar color="#F3ECDA" logo={Logo} />

      <Box sx={{ display: "flex", justifyContent: "center", alignItems: "center" }}>

        <Box sx={{ margin: "200px 0", maxWidth: "1050px", bgcolor: "" }}>
          <Box sx={{ textAlign: "center" }}>
            <Typography sx={{ fontSize: { md: "52px", sm: "44px", xs: "32px" }, fontFamily: "Basely", fontWeight: 500 }}>Terms of Use</Typography>
            <Typography>Updated at January 30th, 2024</Typography>
          </Box>
          <Typography sx={{ margin: "80px 0 50px" }}>Welcome to Lifescript, a platform dedicated to capturing and preserving life stories. By accessing and using the services provided by Lifescript (&quot;Service&quot;), you engage with Lifescript Ltd., located at 16 Avgusta Trayana, Stara Zagora, Bulgaria (&quot;Company&quot;).This document, the Terms of Use (&quot;Terms&quot;), governs your access to and use of our Services, including our website located at www.thelifescript.com (&quot;Website&quot;). These Terms form a binding contract between you and Lifescript Ltd. If you do not agree to these Terms, you should not use the Lifescript Service</Typography>
          <Typography sx={{ fontSize: "18px", fontWeight: 700 }}>Definitions and Key Terms</Typography>
          <Typography sx={{ margin: "20px 0" }}>To ensure clarity, the following terms are defined as follows:</Typography>

          <Box sx={{ maxWidth: "900px" }}>

            <Box sx={{ maxWidth: "70%", margin: "0 0 50px 50px" }}>
              {keyTerms.map((item, index) => <Point
                key={index}
                title={item.title}
                text={item.text}
              />)}
            </Box>
            <Typography sx={{ fontSize: "18px", fontWeight: 700 }}>General Terms of Use</Typography>
            <Box sx={{ maxWidth: "70%", margin: "20px 0 20px 50px" }}>
              {generalTerms.map((item, index) => <Point
                key={index}
                title={item.title}
                text={item.text}
              />)}
            </Box>
            <Typography>By using Lifescript&apos;s Services, you acknowledge that you have read, understood, and agree to be bound by these Terms, including the definitions and key terms. For any inquiries or questions regarding these Terms, please contact us at info@thelifescript.com</Typography>

            <PHeading text="User-Generated Content: Rights, Responsibilities, and Usage" />
            <Typography>
              At Lifescript, we respect the intellectual property rights of our users. When you upload or otherwise provide written materials, photographs, voice and/or video recordings, or other content (collectively, the “Content”) to our platform, you retain ownership of any intellectual property rights in that Content. By submitting your Content, you grant Lifescript a worldwide, perpetual, sublicensable, and transferable license to use the Content to provide our Services to you and for any other purpose you have agreed to, such as marketing purposes. Despite this license, the ownership of your Content remains with you, and we will only use the Content as mutually agreed upon. Please note that while you maintain ownership of your Content, any template or layout in which you arrange or organize such Content through tools and features made available by Lifescript is proprietary to us and will remain with Lifescript. You bear full responsibility for the Content you share with us. If you choose to share the Content publicly, you do so at your own risk, and Lifescript is not liable for any users’ actions in relation to such Content.
            </Typography>
            <Typography sx={{ margin: "20px 0" }}>You represent and warrant that you either own the Content or have the necessary rights to share it with us and allow its use as outlined herein, ensuring that the Content does not infringe, misappropriate, or violate any third-party intellectual property or other rights. For any Content featuring individuals, particularly in videos or photos used for marketing purposes, you must secure permission from all individuals depicted, and if any individual is a minor, consent must be obtained from their parent or guardian.</Typography>
            <Typography>While Lifescript does not typically review customer Content, we may, during the course of providing our Services or in support activities, encounter Content. If we find Content that we determine is illegal or violates our policies, we reserve the right to remove, filter, or refuse to display such Content. However, this does not imply a regular review of Content, so users should not assume such oversight. We are not responsible for any loss or removal of your Content, and we recommend maintaining back-up copies for your records. Additionally, any feedback or suggestions submitted about our Services may be used by Lifescript without any obligation to you.</Typography>
            <PHeading text="Restrictions" />
            <Typography sx={{ marginBottom: "20px" }}>You agree not to, and you will not permit others to:</Typography>
            <Box sx={{ marginLeft: "50px" }}>
              <ul>
                <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform
                  available to any third party.</li>
                <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
                <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Lifescript or its affiliates, partners,
                  suppliers or the licensors of the website.</li>
              </ul>
            </Box>
            <PHeading text="Payment" />
            <Typography sx={{ marginBottom: "20px" }}>Thank you for considering Lifescript. As you explore our products, we are committed to providing you with exceptional service and value. By registering for any of our subscription plans, you acknowledge and agree to the following terms and conditions, which form an integral part of our Terms of Use.</Typography>
            <Box sx={{ maxWidth: "70%", margin: "0 0 50px 50px" }}>
              {payment.map((item, index) => <Point
                key={index}
                title={item.title}
                text={item.text}
              />)}
            </Box>
          </Box>
        </Box>
      </Box>

    </Box>
  )
}

export default TermsAndConditions;

function PHeading({ text }) {
  return <Typography sx={{ fontFamily: "Basely !important", fontSize: { md: "32px", sm: "24px", xs: "20px" }, margin: "50px 100px 20px 0", fontWeight: 600 }}>{text}</Typography>
}

function Point({ title, text }) {
  return <Box sx={{ marginBottom: "20px" }}><Typography sx={{ fontWeight: "bold", marginBottom: "5px" }}>{title}</Typography> <Typography>{text}</Typography></Box>
}